import type { NextPage } from 'next'
import Head from 'next/head'
import Default from '../layouts/Default.layout'
import ImageBox from '../Elements/ImageBox'
import BrandDetails from '../components/BrandDetails'
import Login from '../components/Login'
import MainNav from '../components/MainNav'

import type { layoutPayload } from '../types/global.type'
import Banner from '../Elements/Banner'

const layoutPayload:layoutPayload = [
  {
    id:'top',
    name: "top",
    classes: "test",
    type: 'fixed',
    rows: [
      {
        gridCols: 12,
        gridGap: 8,
        cols:[
          {
            classes: '',
            span: 2,
            components: <>Logo</>
          },
          {
            classes: '',
            span: 8,
            components: <MainNav/>
          },
          {
            classes: '',
            span: 2,
            components: <Login />
          }
        ]
      },
    ],
  },
  {
    id:'hero',
    name: "hero",
    classes: "mt-4",
    type: 'fluid',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            classes: '',
            components: <>
              <Banner 
              className='ex-hero' 
              title='We help to find your better half' 
              subTitle='Demo sub title'
              text='Demo text'
              link='#'
              backgroundColor='#000'
              backgroundImage='hero-1.jpg'
              backgroundOverlay=''
            />
            
            </>
          },
        ]
      },
    ],
  },
  {
    id:'notice',
    name: "notice",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            classes: '',
            components: 
            <>
            notice
            </>
          },
        ]
      },
    ],
  },
  {
    id:'history',
    name: "history",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            classes: '',
            components: 
            <>
            history
            </>
          },
        ]
      },
    ],
  },
  {
    id:'spotlight',
    name: "spotlight",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 2,
        gridGap: 8,
        cols:[
          {
            components: 
            <>
            spotlight
            </>
          },
          {
            components: 
            <>
            notice board
            </>
          },
        ]
      },
    ],
  },
  {
    id:'statistics',
    name: "statistics",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            components: 
            <>
            statistics
            </>
          },
        ]
      },
    ],
  },
  {
    id:'speech',
    name: "speech",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            components: 
            <>
            speech
            </>
          },
        ]
      },
    ],
  },
  {
    id:'gallery',
    name: "gallery",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            components: 
            <>
            gallery carousel
            </>
          },
        ]
      },
    ],
  },
  {
    id:'footer',
    name: "footer",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            components: 
            <>
            footer
            </>
          },
        ]
      },
    ],
  },
]

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Default layoutPayload = {layoutPayload}/> 
    </>
  )
}

export default Home
