import type { NextPage } from 'next'
import Head from 'next/head'
import Default from '../layouts/Default.layout'
import ImageBox from '../Elements/ImageBox'
import BrandDetails from '../components/BrandDetails'
import Login from '../components/Login'
import MainNav from '../components/MainNav'

import type { layoutPayload } from '../types/global.type'
import Banner from '../Elements/Banner'
import AdvanceSearch from '../components/AdvanceSearch'
import Features from '../components/Features'
import CallToAction from '../components/CallToAction'

const layoutPayload:layoutPayload = [
  {
    id:'top',
    name: "top",
    classes: "no-padding",
    type: 'fixed',
    rows: [
      {
        gridCols: 12,
        gridGap: 8,
        cols:[
          {
            classes: '',
            span: 2,
            components: <h1>Pakhi Bhai</h1>
          },
          {
            classes: '',
            span: 8,
            components: <MainNav/>
          },
          {
            classes: '',
            span: 2,
            components: <Login />
          }
        ]
      },
    ],
  },
  {
    id:'hero',
    name: "hero",
    classes: "mt-4",
    type: 'fluid',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            classes: '',
            components: <Banner 
              className='ex-hero' 
              title='We help to find your better half' 
              subTitle='Demo sub title'
              text='Demo text'
              link='#'
              backgroundColor='#000'
              backgroundImage='hero-1.jpg'
              backgroundOverlay=''
            />
          },
        ]
      },
    ],
  },
  {
    id:'advance-search',
    name: "advance-search",
    classes: "",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            classes: '',
            components: <AdvanceSearch className='card p-3 mt-4'/>
          },
        ]
      },
    ],
  },
  {
    id:'ex-features',
    name: "ex-features",
    classes: "ex-features",
    type: 'fixed',
    rows: [
      {
        gridCols: 1,
        gridGap: 8,
        cols:[
          {
            classes: '',
            components: <Features/>
          },
        ]
      },
    ],
  },
  {
    id:'ex-cta',
    name: "cta",
    classes: "mt-4",
    type: 'fixed',
    rows: [
      {
        gridCols: 2,
        gridGap: 8,
        cols:[
          {
            components: <CallToAction
              title='Connect your perfect match'
              bigText='1700'
              subTitle='brids around you'
              action='#'
              btnText='Make an account'
            />
          }
        ]
      },
    ],
  },
]

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Default layoutPayload = {layoutPayload}/> 
    </>
  )
}

export default Home
